fix(adapter): change `use postgres::Rows;` to `use postgres::rows::Rows;`
change `use postgres::Rows;` to `use postgres::rows::Rows;` because of error during compilation:
```sh
error: use of undeclared type name `postgres::Row`
```